version: '3.8'

services:
  mysql:
    image: mysql
    ports:
      - "3308:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root1234
        MYSQL_DATABASE: board_db
    volumes:
      - ./init-sql/:/docker-entrypoint-initdb.d/
    command: --init-file /docker-entrypoint-initdb.d/init-script.sql
    networks:
      - network

  server:
    image: joegukseon/board_server:1.0.0
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_HOST: mysql
      SPRING_DATASOURCE_PORT: 3306
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
    networks:
      - network
    depends_on:
      - mysql
    restart: always

networks:
  network:
    driver: bridge